### ISSUE TITLE
Use semantic names for variables

### ISSUE THREAD

**Issue by joostf** [lhafkamp/minor-frisbee#11]
'numbers' should be 'scores'?!

https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/public/js/io.js#L20-L21

'leftScore' should be '[teamName]Score'?
https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/public/js/io.js#L20-L21

**Comment by lhafkamp** [comment]
Done
