### ISSUE TITLE
Code isn't self-explanatory

### ISSUE THREAD

**Issue by joostf** [lhafkamp/minor-frisbee#12]
It doesn't seem logical that you're selecting the first and third elements. What happende with numbers[1]??
Shouldn't you use a loop or a recursive function here?

https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/public/js/io.js#L20-L21

I think you should consider refactoring the HTML first, the second paragraph element, could be a pseude element for example, which makes your HTML cleaner, and your JavaScript more simple

https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/views/score.ejs#L18-L20

**Comment by lhafkamp** [comment]
Didn't have the time to fix this before the deadline. I did comment above the [2] to make it more clear for the reader.
