### ISSUE TITLE
Use less div elements

### ISSUE THREAD

**Issue by joostf** [lhafkamp/minor-frisbee#14]
Try to make your HTML more semantic
https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/app.js#L68

**Comment by lhafkamp** [comment]
Mmm yeah I started out with divs with the thought that it should be accessible for users that don't support the new semantic elements. Had a discussion about this with Krijn a few weeks ago and he feels like a div with ARIA could be the alternative for some semantic/compatibility related issues.

Either way the current HTML represents more of a test fase right now. Will clean it up later.

**Comment by lhafkamp** [comment]
Made it more semantic anyway.
