### ISSUE TITLE
Bundle controllers for easier requiring

### ISSUE THREAD

**Issue by joostf** [lhafkamp/minor-frisbee#15]
Instead of requiring all controllers on their own, you can require all the controllers in a main controller file (controller/index.js), and expose them there.  So you can require them through one file

https://github.com/lhafkamp/minor-frisbee/blob/08db932cda8c948126bd505ef62a1c4246cacbab/routes/index.js#L3-L5

**Comment by lhafkamp** [comment]
Wes Bos taught me wrong? :(

**Comment by joostf** [comment]
How come?

**Comment by lhafkamp** [comment]
Decided not to do this.
